#-------------------------------------------------------------
#- Docker compose base definition file to run containers.
#-----------------------------------------------------------

version: '3.6'
services:
  api:
    build:
      context: ${API_CONTEXT}
      dockerfile: Dockerfile
      args:
        API_BASE_IMAGE: ${API_BASE_IMAGE}
        api_artifactid: ${api_artifactid}
        api_java_options: ${java_options} ${REMOTE_DEBUG}
    image: ${API_IMAGE}
    ports:
      - "8080:8080"
      - "40500:40500"
    environment:
      io.anbu.proxy.user.limit: 50
      io.anbu.proxy.timeout.seconds: 5 
